<?php
/**
* @file
* A description of what your module does.
*/

/**
 * Implements hook_cron().
 */
function hir_publisher_cron() {
    $day_format = 'dmY';
    $request_time = Drupal::time()->getRequestTime();
    $last_unpublish_run = Drupal::state()->get('unpublish.last.run');
    if (isset($last_unpublish_run)){
        if (date($day_format, $last_unpublish_run) != date($day_format, $request_time)){
            $campaign_processor = Drupal::queue('unpublisher_processor');
            $campaign_processor->createItem(new stdClass());
            Drupal::state()->set('unpublish.last.run', $request_time);
            Drupal::logger('hir_publisher')->notice('UnPublishing scheduled!');
        }
    } else {
        Drupal::state()->set('unpublish.last.run', $request_time);
    }
}